# Generated by Django 2.2.6 on 2022-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220310_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Уникальная строка, содержащая только "безопасные" символы', max_length=15, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
